//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HoaDonMua
    {
        public int ID_HoaDonMua { get; set; }
        public int ID_HangHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public string Removed { get; set; }
        public string Remove_Reason { get; set; }
        public Nullable<double> Gia { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual HoaDonMua HoaDonMua { get; set; }
    }
}
